# Uncomment the next line to define a global platform for your project
 platform :ios, '8.0'

target 'Poppin' do
  use_modular_headers!

  # Pods for Poppin
    pod 'Firebase/Core'
    pod 'FirebaseUI/Storage'
    pod 'Firebase/Auth'
    pod 'Firebase/Database'
    pod 'Firebase/Storage'
    pod 'FirebaseUI/Auth'
    pod 'FirebaseUI/Email'
    pod 'Kronos'

  target 'PoppinTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'PoppinUITests' do
    # Pods for testing
  end

end
