# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Poppin' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Poppin
  pod 'Firebase/Core'
  pod 'FirebaseUI/Storage'
    pod 'Firebase/Auth'
    pod 'Firebase/Database'
    pod 'Firebase/Storage'
    pod 'FirebaseUI/Auth'
    pod 'FirebaseUI/Email'

  target 'PoppinTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'PoppinUITests' do
    # Pods for testing
  end

end
