# Uncomment the next line to define a global platform for your project
 platform :ios, '13.0'

target 'Poppin' do
  use_modular_headers!

  # Pods for Poppin
    pod 'Firebase/Auth'
    pod 'Firebase/Database'
    pod 'Firebase/Storage'
    pod 'Kronos'
    pod 'SFSafeSymbols', '~> 1.2.0'

  target 'PoppinTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'PoppinUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end

post_install do |pi|
    pi.pods_project.targets.each do |t|
      t.build_configurations.each do |config|
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '13.0'
      end
    end
end
